### ISSUE TITLE
IDEAS XRF acquire disable 

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1177]
IDEAS XRF panel acquire button was set to disable when a scan complete and enable when is is saved. It isn't doing this now.

**Comment by iainworkman** [comment]
Okay, the changes I made in c174407 should, theoretically, solve this - though I won't know till I've tried it out on IDEAS - will create a pull request at that point. 

I do have a few conceptual questions about this class, however, and how it's used to conduct XRF scans on IDEAS. If I'm understanding the logic correctly, this allows a user to start an acquisition over a certain dwell period - and then once this has acquired successfully allows the user to ... repeat the same acquisition this time as an actual scan? I think the name of the Save button was confusing me a bit if this is the case, because you're not actually saving what has just been acquired, no? Of course, I might just have the total wrong end of the stick here.

**Comment by dretrex** [comment]
You can make a pull request now and just put the tag "awaiting testing".

**Comment by epengr** [comment]
The save button doesn't trigger another acquisition, it just creates a "scan" that instantly completes and stores the data currently in the buffer.

The act of acquiring (filling the buffer), disables the acquire button so that the user can't inadvertently start a new acquisition (over-writing the buffer) until the data currently in the buffer is saved.  So, the act of saving re-enables the acquire button.  The stop button also re-enables the acquire button so that aborted scans don't prevent you from starting a new one, and it gives the user a way to choose not to save the scan if they don't want to.

**Comment by iainworkman** [comment]
Ahhhh. That makes sense. Wasn't aware of the buffer and the scan completing instantly. 
Thanks Dave

-----Original Message-----

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 4 hours
