### ISSUE TITLE
Add adjustable settling time to the end of mono movements, prior to measurements taken

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1232]
The beamline scientists want to be able to control the settling time for each mono movement. I think this can be done by adding a public setter to the side and main mono classes that calls AMPVControl::setSettlingTime() for the bragg motor. The settling time should be displayed and edited in a widget in the mono configuration view (#1223).

**Comment by helfrij** [comment]
I have a question, @dretrex @davidChevrier. The bragg motor inherits a settling time value from AMPVwStatusControl, with getters and setters. What would be the easiest way to view and edit this value? Using signals and slots with a label or spin box would be one way to go about it (after a settling time value changed signal is added, there isn't one now). Should there be a 'settling time' control of some sort? My thinking was that if there was, it's easy to throw it into any control editor in a view, and setting its value could be added to a scan action.

**Comment by dretrex** [comment]
The settling time can not be a control because it is purely an internal variable.  To do what you've asked, I'd suggest having some sort of spin box and using the public interface of an AMPVwStatusControl (which means you'd have to make your own specific control editor since generic ones won't know about settling time).

The other option is ask if the move done signal can be emitted after the appropriate monitors have come in.  This is another example of status not entirely reflecting what's happening at the lower level.

**Comment by helfrij** [comment]
This issue was actually handled in #1223. Time estimate would have been about 15 minutes. The work I'm considering for this was just 3a882a2, adding a signal to AMPVwStatusControl so that views watching the settling time would be notified of a value change.
