### ISSUE TITLE
Figure out scan problems on Main

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1323]
I've been playing around a little with the XAS scan capabilities on Main. This is a running list of some potentially problematic behaviors that I'm noticing and probably should be addressed. I'm not terribly familiar with this part of AM, so input/comments/suggestions are super welcome.
- [ ] scan configuration doesn't appear to automatically update regions (it used to, I think?)
- [ ] can't seem to retrieve recent past scans from database
- [ ] scan timer... it's not accurate?
- [ ] all exposed detectors show up in the scan data, but some have no data.
- [ ] scaler doesn't seem to stop last measurement, keeps collecting until user tells it to stop.
- [ ] ...

**Comment by dretrex** [comment]
- When you say automatically update regions, what would be causing the regions to update?  Is it an initialization problem? An updating via signals problem?
- Are you getting an error mon that says "could not retrieve from database"? What are the error codes associated with the error?
- Timer is not accurate in what way?  It is based solely on estimates, so if our estimates are off, the timer will not coincide perfectly with the state of the scan.
- The exposed detectors that you won't want to see should be configured in the beamline class with ```setVisible(false)``` and ```setHiddenFromUsers(true)```.  Also, the no data aspect is likely due to various components not being on rather than an error with the detectors.  If this continues to be the case, we'll need to investigate further.
- Is it the last measurement or is it the cleanup actions?

**Comment by dretrex** [comment]
Hey @helfrij, did you close this because we seemed to get everything all running on Friday?

**Comment by helfrij** [comment]
Yup. The point of the issue for me was to come up with a list of things to talk to you and @davidChevrier about. I think we accomplished that on Friday.
