### ISSUE TITLE
Multiple identical XAS scans

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1357]
The BioXAS beamline scientists want to be able to queue up many XAS scans to perform in the workflow, all are identical in terms of regions of interest and dwell time. Right now, the only way to achieve this in Acquaman on BioXAS is to individually add 20 scans to the workflow; instead, it would be nice to be able to select how many scans would be performed for a single configuration. I'm still learning a lot about scans and configurations--do you happen to know if there is already an implementation of this on another beamline @dretrex @davidChevrier @XuetaoLiu-CLS?

**Comment by davidChevrier** [comment]
The easiest way is to use a Loop Action in the workflow and place the scan inside of it. Set it to 20 loops and done. 

In terms of solving this problem, I would strongly advise against putting this in the Scan Configuration View ... it isn't a property of the Scan Configuration itself. That being said, it seems like it could be added to AMScanConfigurationViewHolder so that all configuration types could benefit. A spin box there and some code to place the scan in a loop action and you're set.

**Comment by epengr** [comment]
Repeated scans is common practice for EXAFS. Both VESPERS and IDEAS have the option in the scan configuration to set a number of times to repeat. 

This does exactly as you suggest, and places the scan in a loop. The bottom bar also detects this and adds a widget to change the number of loops. I'd suggest checking out one of those San configs/views

**Comment by helfrij** [comment]
Thanks @davidChevrier and @epengr! I'll look into both of your suggestions tomorrow.

**Comment by XuetaoLiu-CLS** [comment]
This is great. I just got requests from SXRMB on the same feature as well.

X.L.

**Comment by dretrex** [comment]
@epengr is exactly right.  I implemented a way of doing this a long time ago.  You should be able to just change which kind of AMScanConfigurationViewHolder you are using.

**Comment by dretrex** [comment]
Done in #1364.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 3 hours
