### ISSUE TITLE
Add It and I0 to the generic scan configuration

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1618]
It would be useful for the generic scan configuration to automatically grab the It and i0 detectors (if available) from the beamline.

**Comment by dretrex** [comment]
Or more appropriately, be told which detector is It or I0.

**Comment by iainworkman** [comment]
Ahhh, okay. That makes a bit more sense.

**Comment by dretrex** [comment]
After thinking about this, I don't think there needs to be an It specifier.  Since the source would already be handled correctly.  The only exception is the specific case of doing an XAS scan using the generic tool, but that's fine that it doesn't do it by default because there are already scans that perform that task.

**Comment by dretrex** [comment]
Time Estimate: 2 hours

**Comment by dretrex** [comment]
Done in #1700.
