### ISSUE TITLE
Binning analysis block editors may be unstable

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1626]
It has been reported (specifically with AM3DBinningABEditor) that if you enter an invalid end point that the program will crash.  It is not entirely surprising to me that such a crash exists.  If there is a possible crash bug in this editor, it is likely inside all the other binning editors as well.

**Comment by helfrij** [comment]
After talking to @dretrex today:

Original/primary problem: the cause of this problem is likely that low point > high point. A solution could be to not allow view changes to modify the analysis block if this condition is met. Check 1D, 2D, and 3D (+?) analysis block editors as well, they may have the same problem.

Secondary/related problem: High and low values not stored to the database. When exported to database, column of zeroes is result. It's likely that a setModified(true) statement was missed, or the a Q_PROPERTY wasn't included. Check all-D binning blocks and AM2DSummingBlock, as they may have same errors.

**Comment by dretrex** [comment]
Done in #1713.
Time Estimate: 20 minutes
