### ISSUE TITLE
14) Visible Light/Full Beam Questions

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1683]
We need some answers from Tom Regier regarding how visible light vs. full beam is intended to work on the new end station. 

Previously visible light differed from full beam by placing crown glass in the way of the beam, to remove the x-ray component. We need to find out if this is still the case for the current end station.

**Comment by regiert** [comment]
The visible light will still be a required user option for both
endstations.  Upon pressing the zero order light, the desired action will
be for the grating to move to the zero order angle and for the final valve
in the beamline (immediately upstream of the KB mirror VVR1611-4-I10-08) to
close.  When the visible light button is pressed again, the grating angle
will return to the angle corresponding to the energy that the beamline was
set to before the button was pressed for the first time.  In order to
prevent the user from inadvertently exposing the KB mirrors, silicon
nitride window and their sample to the full beam, the desired action of
pressing 'Beam On' when zero order light is the presentation of dialogue
box with an option to move back to first order or cancel the beam on
request.  The only way to get full beam in the endstation will therefore be
through the use of an alternative software (IDAV or Beamline Master) or by
command line.  This will ensure that beamline staff can still generate the
full beam condition (to clean the mirrors) but the users cannot.


Tom Regier, PhD.
Beamline Scientist, SGM Beamline
Canadian Light Source, Inc.
tom.regier@lightsource.ca
(306) 657 - 3733

**Comment by iainworkman** [comment]
Thanks for clearing that up Tom. I'm going to close out this issue, but your response will remain as reference. If you think of anything else regarding this, feel free to add it here.

**Comment by davidChevrier** [comment]
Time Estimate: 1 hour
