### ISSUE TITLE
8) Continuous Scan Infrastructure (1D)

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1684]
Once the energy coordinator is in place it will be necessary to create an interface through which continuous 1d scans can be performed upon a provided generic control. 

PR: #1709

**Comment by dretrex** [comment]
Technically, this will be required for the Hexapod too.

**Comment by iainworkman** [comment]
To do:
- [ ] Figure out why scanning backwards isn't working.
- [ ] Allow the necessary classes access to the trajectory and grating encoder translation value functions.
- [ ] Refine the algorithm for distinguishing the start and end of the scanning portion of a move.

**Comment by dretrex** [comment]
I saw from @davidChevrier's email that backwards scans isn't working.  Do we have any more information on that @iainworkman?  I can potentially brainstorm something up as well.

**Comment by iainworkman** [comment]
I'm looking at it in the coordinator. Things that were working don't seem
to be any more. The velocity calculation is coming out with a different
value when moving backwards. And not just a negative version, a totally
different value. I'm trying to track it down.

**Comment by davidChevrier** [comment]
Items left to complete:
- [ ] Generalize detector actions in the assembler. This will require the new scalerChannelDetector to properly implement sharedTriggerSource to be fully general.
- [ ] Add the actual encoder start point, maybe as a custom detector emulator
- [ ] Issue #1714 
- [ ] Fix the up/down scanning ... because down scanning will not fill the datastore correctly at the moment. It's just an iterating issue really.

**Comment by davidChevrier** [comment]
@iainworkman is doing the actual work for implementing #1714 in #1724. We leave that for it's own branch and merge it back into sgmupgrade at some point. I'm considering this done otherwise.

**Comment by davidChevrier** [comment]
Time Estimate: 35.5 hours
