### ISSUE TITLE
BioXAS: The regions of interest are not being set to XAS scans

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1844]
It appears that the Ge detector is never being connected in BioXASAppController line 104.  This is causing regions of interest to not be set to the BioXASXASScanConfiguration and therefore the regions of interest are ignored when doing an XAS scan.

**Comment by helfrij** [comment]
The problem ended up being with a misplaced connect statement: user configurations were connected to after they would have emitted their loadedFromDb() signals. This issue exposed another problem in BioXASXASScanActionController where the Ge detector's normalization ABs were being passed invalid data sources. This problem was fixed in this issue as well.

Time Estimate: 2 hours.
