### ISSUE TITLE
Export XRF button bring up unpopulated scan browser

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2106]
AMXRFDetailedDetectorView::onSaveButtonClicked() uses chooseScanDialog_->setFilterRegExp("X(|-)Ray Fluorescence Scan"); which doesn't match the default XRF scan technique which seems to be "Generic Scan"... at least on IDEAS.

Might I suggest that we change it to filter on scan name, and search for "XRF Scan - %1").arg(detector_->name()), which would then only show ones that have not been renamed?

**Comment by dretrex** [comment]
I ran into this when I was working on the generic XRF scan controller.  The problem comes from what @iainworkman pulls in for the lightweight model.  Unfortunately, it just fell by the wayside.  @iainworkman, do you remember which argument we needed to change here?

**Comment by epengr** [comment]
@iainworkman, @dretrex, did another get done / thought of regarding this?  Is it something that I can tackle of is it closely related to @iainworkman's work such that I shouldn't bother?

**Comment by iainworkman** [comment]
Okay, I think I have the root of this figured.
The detector view is searching the 'Technique' column (which maps to scanType field of AMLightweightScanInfo). This is populated by obtaining the AMDbObjectType from the AMScan_table of the database, and then using this value to match against the description field from the AMDbObjectTypes_table. 

Since most scans have now been made generic (and so only use AMScan to store their data) this basically comes back as 'Generic Scan' every time. 

Having spoken with @epengr, this seems to actually be forking into two issues:
- Making the technique field of the lightweight scan info meaningful
and
- Making the XRF detailed detector view export function more user friendly

This is because the export function should be more convenient than just showing all XRF scans. Ideally it should display unexported XRF scans. @epengr suggested that keying in on the default name of the XRF scan might be a better idea, as when users then renamed the scan it would vanish from the list.

**Comment by epengr** [comment]
Completed in #2273

Time Estimate: 20 minutes

**Comment by iainworkman** [comment]
Time Estimate: 30 minutes
