### ISSUE TITLE
Add option to add detector to a configuration without exporting it 

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2194]
The BioXAS team wants to be able to add I0, I1, I2 detectors to a scan configuration and have the ability to use processed I0, I1, and I2 data in the scan, instead of the raw data.

**Comment by dretrex** [comment]
Hey @helfrij, I renamed the issue to better reflect what they meant.  Since it isn't possible to include a detector without having it as a data source (you'd never be able to use analysis blocks that way), it seems like they just don't want non-dark current corrected datasources as columns in the exported file.

**Comment by helfrij** [comment]
Sounds good @dretrex.

**Comment by helfrij** [comment]
It looks like there is an AMExporterOptionGeneral method `includeAllDataSources()` that is normally set to true, but can be set to false. That's probably the first step to solving this problem, and would likely be done in BioXAS.h.

There are other AMExporterOptionGeneral methods for adding and removing data sources, and setting whether or not they are 'required': `addDataSource(...)`. This may be the second part. I guess I wonder, would these data sources be set in BioXAS.h as well, @dretrex?

**Comment by dretrex** [comment]
They could be.  You could also have it dynamically filled as you add the corresponding data sources in the scan controller since when you call BioXAS::buildExporterOption it returns you a valid option object.  I'd say you probably want to manipulate that but have the `includeAllDataSources()` set to false in the BioXAS.h method.

**Comment by helfrij** [comment]
That makes sense. Thanks, @dretrex.

**Comment by helfrij** [comment]
Done in #2227.

Time Estimate: 1 day.
