### ISSUE TITLE
PGMAcquaman startup issue

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2442]
There are two issues with PGM Acquaman launching:
- [ ]  When using the same proposal number as before, the dialog to confirm data storage should not visible
- [x] When launching Acuqaman, the user MUST choose / create a run before he starts to use Acquaman

**Comment by mButlerDM** [comment]
@XuetaoLiu-CLS These issues seem to affect other beam lines as well.

**Comment by mButlerDM** [comment]
I addressed the second issue by hiding the main window while the first run dialog is up.

The second issue requires updating the CLSNetworkDirectorySynchronizer to use the new userBasedDataStorage setting in the ini.

**Comment by mButlerDM** [comment]
@XuetaoLiu-CLS When using the same proposal number and having the dialog show up at every launch, the issue is caused by a file system permission error. CLSNetworkDirectorySynchronizer tries to create a remote directory at /home/pgm/... and is unable to do so. Since the folder does not exist it thinks it's a first run. 

Should this location be adjusted?

**Comment by mButlerDM** [comment]
@XuetaoLiu-CLS Does #2457 address the first run wizard issue here?

**Comment by XuetaoLiu-CLS** [comment]
@mButlerDM I just want to chat with you about this. I think it solved this issue. I didn't see the wizard anymore for the second run :)

**Comment by mButlerDM** [comment]
Time Estimate: 1 Hour
