### ISSUE TITLE
AMControl Missing Signal for Range Changed

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#484]
@regiert recently had Acquaman open on the SGM and changed the DRV_HIGH and DRV_LOW values on a motor. They changed in EPICS but Acquaman was still limiting the values he could put in. When Acquaman was restarted the new values were detected.

**Comment by iainworkman** [comment]
Okay, I'm going to need this for the hexapod, both in terms of transforming a coordinate system (which invariably results in the range being altered) and because whenever a move is made in a given axis it alters the limits in all the other axes.

**Comment by dretrex** [comment]
Sounds good.  Let me know if you run into any issues.  I also took the liberty of moving this to a different pipeline for you since you don't have access to chrome.

**Comment by iainworkman** [comment]
Encountered a difference between the epics documentation for R3.14.12 on the website, and what is in the cadef.h file. The code seems to not wish to subscribe to the DBE_PROPERTY event.

This may be an issue with the epics documentation, or because of some wizardry done with the epics libraries here.

**Comment by iainworkman** [comment]
Downloaded the R3.14.12 and looked in the header files there, and it _is_ a difference between the documentation and the release not something custom at the cls.
 I spoke with Ru, and he suggested that monitoring the limits would be possible if instead of creating a subscription to the properties of the PV we set up a value subscription directly to the PVs OPRH, OPRL, DRVH and DRVL.

So, there are basically three options for this which are progressively higher level, and less general
1. Alter AMProcessVariablePrivate so that in its constructor it attempts to connect to pvName.OPRH, pvName.OPRL, pvName.DRVH and pvName.DRVL. If these connections are successful we then create a subscription to them which handles the value changes.
2. Alter AMPVControl so that it creates AMProcessVariables for its limits. The disadvantage of this is that it would spit out errorMons for all PVs which don't have limits. This could be worked around with an additional constructor argument ``` bool hasLimits = false ```
3. This would only apply to #1569 , but the pseudo-motor could connect to the DRVH and DRVL directly, and update it's limits accordingly when they change.

**Comment by dretrex** [comment]
I would generally be more in favour of the second option.

**Comment by iainworkman** [comment]
Seems like a good compromise, and also means I don't have to fanny around in AMProcessVariablePrivate :+1:

**Comment by dretrex** [comment]
That is definitely one of the main reasons lol

**Comment by iainworkman** [comment]
I deleted this branch and started again, as the final solution will just involve adding moving the min/max changed signals from AMPseudoMotor up to AMControl, and then creating the mechanism to monitor the limits in AMPVControl.

**Comment by iainworkman** [comment]
Time Estimate: 20 hours
